[build]
publish = "."
command = ""

# Helpful security headers (adjust as needed)
[[headers]]
for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "no-referrer"
  X-Frame-Options = "DENY"
